version: '3.8'

services:
  safar-postgres:
    image: postgis/postgis:15-3.3
    container_name: safar-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: safar_secure_password_2026
      POSTGRES_DB: safar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  safar-redis:
    image: redis:7-alpine
    container_name: safar-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
