name: rider
description: "SAFAR Rider Native Flutter Application"
publish_to: 'none'
version: 1.0.2+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  socket_io_client: ^2.0.3+1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
